2021-10-01 16:25:25,729 Downloading and reading artifact
wandb: ERROR Project obara/exercice_5 does not contain artifact: "preprocessed_data.csv:latest"
Traceback (most recent call last):
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project obara/exercice_5 does not contain artifact: "preprocessed_data.csv:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/obara/nd0821-c2-build-model-workflow-exercises/lesson-2-data-exploration-and-preparation/exercises/exercise_6/solution/run.py", line 122, in <module>
    go(args)
  File "/Users/obara/nd0821-c2-build-model-workflow-exercises/lesson-2-data-exploration-and-preparation/exercises/exercise_6/solution/run.py", line 21, in go
    artifact = run.use_artifact(args.input_artifact)
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/Users/obara/miniforge3/envs/mlflow-3741a694e63e8adb2c01612449fee7db5519ae32/lib/python3.9/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project obara/exercice_5 does not contain artifact: "preprocessed_data.csv:latest"
